// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ipc} from '../models';

export function CheckNewInstall():Promise<boolean>;

export function Connect(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Disconnect():Promise<string>;

export function GetGUIVersion():Promise<string>;

export function GetInitialConfig():Promise<main.InitialConfig>;

export function GetLogs():Promise<string>;

export function GetSavedConfig():Promise<Record<string, any>>;

export function GetStats():Promise<ipc.Stats>;

export function GetStatus():Promise<ipc.Status>;

export function SaveConfig(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ShowAbout():Promise<void>;
