// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNewInstall() {
  return window['go']['main']['App']['CheckNewInstall']();
}

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetGUIVersion() {
  return window['go']['main']['App']['GetGUIVersion']();
}

export function GetInitialConfig() {
  return window['go']['main']['App']['GetInitialConfig']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPublicIPInfo() {
  return window['go']['main']['App']['GetPublicIPInfo']();
}

export function GetSavedConfig() {
  return window['go']['main']['App']['GetSavedConfig']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}
